coinbase/mesh-sdk-go

fetcher/construction.go
Removes need for API client to be passed to transaction construction fetcher.
API client argument needs to be initialized and configured separately
Deletes function argument and uses fetcher instance property
None
=> Remove extraneous client arg from construction fetcher

asserter/network.go, asserter/network_test.go
Currently, `asserter/network.go` will raise an error if `/network/status` is returned as a method in the `Options.Methods` array. This was originally done because listing `/network/status` on a call to `/network/status` seemed redundant. However, the Rosetta documentation provides no indication that `/network/status` should not be returned.
Instead of updating documentation not to include `/network/status` (which would cause unnecessary friction in development), it has been added to `AllowedMethods`.
* Export `AllowedMethods`
* Alphabetize `AllowedMethods`
=> Add /network/status to allowedMethods

README.md, templates/README.mustache
The current godoc link on the readme points to the [0.0.3 release](https://pkg.go.dev/github.com/coinbase/rosetta-sdk-go@v0.0.3?tab=overview) instead of master.
Fix the link to point to [master](https://pkg.go.dev/github.com/coinbase/rosetta-sdk-go?tab=overview).
=> Update godoc link

asserter/README.md, client/README.md, fetcher/README.md, models/README.md, server/README.md, templates/docs/client.md, templates/docs/models.md, templates/docs/server.md
Current godocs links direct to overview page instead of docs page.
Change links to point to docs page.
=> Change link to docs page

asserter/asserter.go, asserter/asserter_test.go, asserter/block.go, asserter/block_test.go, asserter/construction.go, asserter/construction_test.go, fetcher/block.go, fetcher/construction.go, fetcher/mempool.go
`Asserter.NewWithResponses` function arguments were not checked for correctness and the function did not have any tests.
Added assertion for inputs and added tests. This caught a few issues in tests that were initializing the asserter with incorrect responses.
=> Add Asserter Tests

asserter/block.go, asserter/request_test.go, examples/fetcher/main.go, examples/server/services/block_service.go, examples/server/services/network_service.go, go.sum, server/api.go, server/api_account.go, server/api_block.go, server/api_construction.go, server/api_mempool.go, server/api_network.go, templates/server/api.mustache, templates/server/controller-api.mustache
The autogenerated servicer interface methods did not include the request context as a parameter.
Each servicer method now includes context as a parameter.
=> Add Servicer Context

asserter/account.go, asserter/account_test.go, fetcher/account.go, fetcher/construction.go
* Calls to fetch an account balance in the `fetcher` did not allow for providing a `PartialBlockIdentifier` for a historical balance query
* Calls to fetch an Account balance in the `fetcher` did not return account metadata
Fixed both issues. Also added an assertion to ensure that historical balance query responses contain a `BlockIdentifier` related to the query `PartialBlockIdentifier`.
Once this is merged, it will be possible to perform rosetta-validator reconciliation while syncing.
=> Add historical balance lookup

parser/balance_changes.go, parser/balance_changes_test.go, parser/parser.go
Fast follow to #21 to make the `ExemptOperation` type public.
=> Make ExemptOperation public

asserter/account.go, asserter/account_test.go, parser/group_operations.go, parser/group_operations_test.go
When parsing an `OperationGroup` it is often useful to know which currencies were present and if there were any operations with `op.Amount == nil`.
`OperationGroup` now has a slice of `*types.Currency` that contains all currencies present in an `OperationGroup` and a boolean indicating if any operation has a `nil` Amount.
=> Track OperationGroup Currencies

parser/group_operations.go, parser/group_operations_test.go
It can be very useful for clients to receive a **deterministic ordering** of `OperationGroups` and `Operations` within an `OperationGroup` when calling `GroupOperations`.
Sort all `OperationGroups` in a transaction by the lowest `OperationIdentifier.Index` in each group. Then, sort all `Operations` in an `OperationGroup` by `OperationIdentifier.Index`, ascending.
=> Sort OperationGroup Results

reconciler/configuration.go, reconciler/reconciler.go, reconciler/reconciler_test.go
When restarting the `Reconciler`, the record of previously seen accounts and the inactive reconciliation queue is discarded. Upon restart of the reconciler, there is no way to repopulate this record of previously seen `AccountCurrency`. In the `rosetta-cli`, this can lead to inactive reconciliation not checking all accounts if reconciliation is restarted using the same datastore (common practice).
* Allow the `Reconciler` to be instantiated with previously seen accounts.
* Add a method `NewAccountSeen` to the `Reconciler.Handler` that is called whenever a new account is observed. This allows the client to store these new accounts persistently (to later provide for reconciler instantiation).
=> Initialize Reconciler with Previously Seen Addresses

reconciler/configuration.go, reconciler/reconciler.go
On initialization, the reconciler prints out each previously seen account that was added (super annoying when there are more than 10 previously seen accounts). Also, the reconciler prints a confusing log message when it is waiting to start inactive reconciliation.
* Log the number of previously seen accounts initialized instead of each account.
* Log a clearer message when waiting to start the inactive reconciler.
=> Better Logging on Reconciler

reconciler/configuration.go, reconciler/reconciler.go, reconciler/reconciler_test.go
Fix #28.
After some initial consideration to create a shared reconciliation goroutine pool (that always preferred active reconciliations to inactive reconciliations), I decided to stick with the 2 pool route and add a configuration to control the concurrency of each.
There are certain cases where you would not always want to prefer active reconciliations to inactive (for example, in the case where there are so many active reconciliations queued that you never do inactive reconciliations) so I opted for this dual configuration option en lieu of developing some complicated heuristic.
=> Add Reconciler Active/Inactive Concurrency Configuration

fetcher/account.go, fetcher/account_test.go, fetcher/block.go, fetcher/block_test.go, fetcher/fetcher.go, fetcher/network.go, fetcher/network_test.go, fetcher/utils.go, reconciler/reconciler.go
* If context is cancelled, retry methods in the `fetcher` package return an incorrect error (exhausted retries instead of context error).
* If context is cancelled, the reconciler can silence the `ctx.Err()` and return `nil` instead.
Return the correct error.
=> Return Correct Error on Context Cancellation

reconciler/reconciler.go
It is useful for users of the `reconciler` package to parse the reconciliation error type but clients must define their own types because they are not exported.
Export reconciliation types.
=> Export Reconciliation Types

.circleci/config.yml, parser/match_operations.go, parser/match_operations_test.go
Fixes #35 
Return `[]*types.Operation` from `MatchOperations` instead of `[]int`.
=> Return ops instead of indicies

parser/match_operations.go, parser/match_operations_test.go
Fixes #38, #39, #40.
Return a new `Match` struct instead of `*types.Operation` from `MatchOperations`. This new struct allows for multiple `*types.Operation` to be matched with a given `OperationDescription`.
=> Improve Matching Functionality

parser/match_operations.go, parser/match_operations_test.go
Fixes #42.
Add an `Optional` field to the `OperationDescription` struct.
=> Optional `OperationDescription` in Parser

Makefile, parser/match_operations.go, parser/match_operations_test.go
Fixes #44 and Fixes #45 
* Only run `test-cover` if `COVERALLS_TOKEN` is not missing.
* Add `EqualAddresses` to `OperationDescription`
=> Add `EqualAddresses` to `OperationDescription`

asserter/construction.go, asserter/construction_test.go, asserter/request_test.go, codegen.sh, templates/marshal.txt, types/marshal_test.go, types/public_key.go, types/signature.go, types/signing_payload.go
#55 does not automatically unwrap hex-encoded bytes for users of the SDK. This means that developers that use the SDK need to duplicate hex decoding/encoding code whenever interacting with these encoded bytes.
* Implement a custom JSON marshaler/unmarshaler that automatically encodes/decodes bytes to hex.
* Use codegen scripts to automatically add this custom JSON marshaler/unmarshaler to any types that have hex encoded bytes.
=> Automatically Encode/Decode Hex

README.md, keys/keys.go, keys/keys_test.go, keys/signer_edwards25519.go, keys/signer_edwards25519_test.go, keys/signer_secp256k1.go, keys/signer_secp256k1_test.go, keys/types.go, reconciler/README.md, syncer/README.md
* Update README links to new website
* Change `KeyPair` to get rid of redundant `CurveType` usage
* Change `ed25519` signer to `edwards25519` signer
=> Miscellaneous Fixes Before Release

reconciler/configuration.go, reconciler/reconciler.go, reconciler/reconciler_test.go
Fix #65 
* Ensure all seen accounts are added to the `inactiveAccountQueue` even if we are far behind tip
* Ensure accounts aren't leaked from the `inactiveAccountQueue` (could occur if accounts
* Improve performance by changing frequent operation (`seenAccounts` check on each block) from `O(n)` to `~O(1)` (caused reconciler to get much slower as more accounts seen).
* Ensure `inactive reconciler` respects the `highWaterMark` (so useless queries are not performed during syncing).
* Fix edge case issue where an account could be added to the queue multiple times (in different go routines). This fix was possible because a lookup is performed while holding the lock and that lookup is now `~O(1)` time now.
We could further optimize the `reconciler` to cache balances it retrieved when behind …
=> Inactive Reconciler Performance when --lookup-balance-by-block=false

reconciler/reconciler.go
Fixes #67
Fix a panic in the reconciler when attempting to access an element in an empty array. This regression was introduced in #66.
**INCREASE TEST COVERAGE**
=> Handle empty inactive queue correctly

reconciler/reconciler.go
Fixed a race condition where the size of the `inactiveQueue` could have been mutated by the time it's logged
which leads to logging inaccuracy
=> Fix a race condition that can lead to logging inaccuracy

asserter/construction.go, asserter/construction_test.go, fetcher/construction.go
Fixes #73 
Fixes a bug where `Asserter.ConstructionParseResponse` raises an error if there are no signers, when it shouldn't for unsigned transactions.
=> Bug when asserting ConstructionParseResponses

syncer/syncer.go
When calling `syncer.Sync` with an `endIndex != -1`, the `syncer` will attempt to fetch blocks past the `tip` returned by `CurrentBlockIdentifier.Index`.
In `nextSyncableRange`, we always fetch the `NetworkStatus` and compare it to the `endIndex` we are attempting to sync to. If we are attempting to get to an `endIndex` greater than `CurrentBlockIdentifier.Index`, we should handle gracefully getting there (as we wait for blocks).
=> [BUG] Syncer Fetches Invalid Index when endIndex populated

.gitignore, parser/match_operations.go, reconciler/reconciler_test.go
Fixes # .
Update comparison match logic for opposite amounts
- Add more validation on match operations
- Improve time complexity of comparison logic from O(N^2) -> O(N)
use a single for loop instead of nested to simply things
=> [CHORE] Update comparison match logic for opposite amounts

parser/intent.go, parser/intent_test.go
Related Issue: https://github.com/coinbase/rosetta-cli/issues/68
Compare intended vs observed operations and singers. This is useful when comparing the input to the `Construction API` with the output of `/construction/parse`.
=> Compare Intent vs Observed Operations and Signers

fetcher/configuration.go, syncer/syncer.go
Related Issue: https://github.com/coinbase/rosetta-cli/issues/64
Make `syncer` less verbose at tip and add ability to provide custom timeout for requests.
=> HTTP Timeout + Less Verbose Syncer

examples/server/main.go, server/logger.go, server/routers.go, templates/server/logger.mustache, templates/server/routers.mustache
This makes the middlewares offered by the server package optional. This
allows full customization by implementations.
Fixes #59
=> Make middlewares optional

parser/intent.go, parser/intent_test.go
* Modify `ExpectedOperations` to allow for asserting success on matched operations
* Print out all missing matches in `ExpectedOperations` error
=> Assert Successful Intent

parser/balance_changes.go, parser/match_operations.go, parser/match_operations_test.go
Related PR: https://github.com/coinbase/rosetta-cli/pull/81
This _should_ be the last PR before the next release. It changes the logging verbosity for exempt operations and adds support for parsing the new `Coin` model when matching operations in the `parser`.
=> Parse Coins

syncer/syncer.go, syncer/syncer_test.go
Related PR: https://github.com/coinbase/rosetta-cli/pull/88
Regression introduced in: #89
The context returned by `errgroup.WithContext` is canceled as soon as `g.Wait` returns. If this canceled context is passed to a handler or helper, it can have unintended consequences (some functions return immediately if the context is canceled).
Source: https://godoc.org/golang.org/x/sync/errgroup
=> [BUG] ErrGroup Context Cancelation

asserter/account.go, asserter/account_test.go, asserter/construction.go, asserter/construction_test.go, asserter/server.go, asserter/server_test.go, client/api_block.go, client/api_construction.go, client/client.go, codegen.sh, fetcher/block.go, fetcher/block_test.go, syncer/syncer.go, syncer/syncer_test.go, types/block_response.go, types/construction_metadata_response.go, types/construction_preprocess_request.go
Blocked by: https://github.com/coinbase/rosetta-specifications/pull/35 and `v1.4.2` release
This PR adds support for syncing omitted blocks and for populating the new suggested fee-related fields that were added in `v1.4.2`.
=> Support Omitted Blocks

keys/keys.go, keys/keys_test.go
This adds the `ImportPrivKey` function to the keys package, and allows users to pass in a hex-encoded privkey string to get a KeyPair.
This will be used in `rosetta-cli` where users can specify their prefunded addresses' privkeys in hex format in their config files.
=> Add ImportPrivKey function to keys package

fetcher/account.go, fetcher/block.go, fetcher/construction.go, fetcher/fetcher.go, fetcher/mempool.go, fetcher/network.go, syncer/syncer.go, syncer/syncer_test.go
Related PR: https://github.com/coinbase/rosetta-cli/pull/103
To better trace the origin of different errors, we define typed errors that can be examined by the caller.
=> Add Typed Errors to Syncer and Fetcher

fetcher/account.go, fetcher/account_test.go, fetcher/block.go, fetcher/block_test.go, fetcher/fetcher.go, fetcher/mempool.go, fetcher/network.go, fetcher/network_test.go, fetcher/utils.go
Fixes # .
In order to allow consumers of the fetcher to parse errors upstream, we need to expose the Rosetta types.Errors being returned from our API calls.
Defined an ErrorRes struct that wraps both the Go error and Rosetta error being returned from API calls, and returning that from the fetcher instead.
=> exposing Rosetta types.Error in fetcher

Makefile, fetcher/account.go, fetcher/account_test.go, fetcher/block.go, fetcher/block_test.go, fetcher/network.go, fetcher/network_test.go, fetcher/utils.go, statefulsyncer/stateful_syncer.go
Related PR: #99 
This PR fixes a bug in statefulsyncer when `fetchErr` is nil.
=> [BUG] Err Handling in statefulsyncer

fetcher/account.go, fetcher/account_test.go, fetcher/block.go, fetcher/block_test.go, fetcher/network.go, fetcher/network_test.go
Related PR: #105 
In #105, we introduced a small bug where canceling context doesn't always return a context.Canceled error. This created a flaky test that caused master tests to fail:
https://app.circleci.com/pipelines/github/coinbase/rosetta-sdk-go/586/workflows/1c59e0e3-c228-4718-b784-0d862d32648d/jobs/4204
This PR fixes this issue!
=> [BUG] Ensure canceling context returns the correct error

constructor/executor/job_test.go, constructor/executor/worker_test.go, storage/coin_storage.go, storage/coin_storage_test.go
When adding/removing a block to/from storage, we iterate over transactions in the order they are represented. If a coin is created and destroyed in the same block and transactions are ordered where the "add coin" op is after the "remove coin" op, we will not remove the newly created coin (coin removal is a no-op if the coin cannot be found).
There are 2 ways to fix this bug:
* skip coins that are added/removed in the same block
* process coin additions before removals
I opted for the first fix because it reduces the amount of DB activity when adding blocks without restricting functionality (partially applied coin state is never queried).
=> [BUG][Storage] Incorrect handling of coins created and spent in same block

constructor/coordinator/coordinator_test.go, storage/coin_storage.go, storage/coin_storage_test.go
Related PR: #122 
This PR ensures that an error is thrown if a coin appears twice in the same block.
=> [BUG] CoinStorage Same Block Duplicate

examples/fetcher/main.go, fetcher/fetcher.go, fetcher/fetcher_test.go, fetcher/utils.go, utils/utils.go
Fixes #96
This PR makes it possible to initialize the `fetcher` with some non-default network. This is useful for Rosetta implementations that support multiple networks.
=> [Fetcher] Initialize with non-primary network

storage/badger_storage.go
=> [BUG] Increase Max Table Size for Performance Option

asserter/construction.go, asserter/construction_test.go, asserter/errors.go, asserter/server.go, asserter/server_test.go, client/client.go, codegen.sh, fetcher/construction.go, types/construction_metadata_request.go, types/construction_parse_response.go, types/construction_payloads_request.go, types/construction_preprocess_response.go, types/curve_type.go, types/signature_type.go
Closes #130 
This PR adds support for `v1.4.3` of the Rosetta Specification.
=> Upgrade to v1.4.3 spec

constructor/coordinator/coordinator.go, constructor/coordinator/coordinator_test.go, constructor/coordinator/types.go, fetcher/construction.go, mocks/constructor/coordinator/helper.go, storage/key_storage.go
Related Issue: https://github.com/coinbase/rosetta-cli/issues/112
The [`v1.4.3` release of the Rosetta Specification](https://github.com/coinbase/rosetta-specifications/releases/tag/v1.4.3) allows a Rosetta implementation to request the PublicKeys of any number of AccountIdentifiers for calls to `/construction/metadata` and `/construction/payloads`.
This PR adds support for the `fetcher` to accept PublicKeys in calls to `/construction/metadata` and `/construction/payloads` and for the `constructor` to inject requested public keys automatically.
* Update rosetta specification to return `AccountIdentifier` in `ConstructionDeriveResponse` and `SigningPayload` (non-breaking by adding field + deprecating)
* Store keys under `AccountIdentifier` instead of address (there may be multiple keys …
=> [Constructor] Inject Public Keys During Transaction Construction

syncer/syncer.go, syncer/syncer_test.go
Some users of the `syncer` cannot respond to the `Block` method if any parent block is not on the canonical chain (ex: an indexer using outputs of the parent block). This PR allows these users to pass `ErrOrphanHead` instead of a partially populated block (missing the transactions that can't be populated) to trigger a re-org.
=> [Syncer] Allow Caller to Trigger Reorg

Makefile, asserter/errors.go, errors/utils.go, errors/utils_test.go, keys/errors.go, keys/errors_test.go, keys/signer_edwards25519.go, keys/signer_secp256k1.go, keys/signer_secp256k1_test.go, parser/errors.go, parser/errors_test.go, parser/intent.go, parser/match_operations.go, utils/utils.go
Fixes # .
continuing from this PR: [https://github.com/coinbase/rosetta-sdk-go/pull/102](https://github.com/coinbase/rosetta-sdk-go/pull/102)
and this PR: [https://github.com/coinbase/rosetta-sdk-go/pull/129](https://github.com/coinbase/rosetta-sdk-go/pull/129)
we want to use named errors in the SDK to improve the debugging experience
this PR also includes some minor changes in /keys
added errors.go and an ErrParser() function to check if an error was thrown by the parser
=> [Parser] typed errors overhaul

.circleci/config.yml, storage/badger_storage.go, storage/badger_storage_test.go, storage/balance_storage.go, storage/block_storage.go, storage/broadcast_storage.go, storage/buffer_pool.go, storage/coin_storage.go, storage/coin_storage_test.go, storage/compressor.go, storage/compressor_test.go, storage/counter_storage.go, storage/job_storage.go, storage/key_storage.go, storage/storage.go
Blocked by (rebased on): https://github.com/coinbase/rosetta-sdk-go/pull/135
This PR makes it possible to lookup Coins by their identifier. This is useful for building indexers on top of the `syncer` package.
- As a rule of thumb, only `Put` in the `sync.Pool` if you created the bytes (otherwise very hard to track where duplicate additions could be).
- Additionally, never `Put` any inputs into the `sync.Pool`. The responsibility to reclaim `bytes` should be on the caller.
=> [Storage] Lookup by CoinIdentifier

fetcher/account.go, fetcher/block.go, fetcher/configuration.go, fetcher/construction.go, fetcher/errors.go, fetcher/fetcher.go, fetcher/mempool.go, fetcher/network.go, storage/badger_storage.go, storage/badger_storage_test.go, storage/balance_storage.go, storage/broadcast_storage.go, storage/coin_storage.go, storage/key_storage.go, storage/storage.go
Blocked by (rebased on): #136
When using the `fetcher` concurrently, it is sometimes possible to surpass the port allocation on the OS. After some research, I determined this was due to not effectively reusing connections. Based on the info in [this thread](https://stackoverflow.com/questions/37774624/go-http-get-concurrency-and-connection-reset-by-peer), I have tuned `IdleConnTimeout`, `MaxIdleConns`, and `MaxIdleConnsPerHost` accordingly.
=> [Fetcher] Improve Connection Reuse

storage/badger_storage.go, storage/badger_storage_test.go, storage/balance_storage.go, storage/block_storage.go, storage/broadcast_storage.go, storage/coin_storage.go, storage/compressor.go, storage/compressor_test.go, storage/job_storage.go, storage/key_storage.go, storage/key_storage_test.go, storage/storage.go, utils/utils.go
Replaces #140 
We wait to reclaim memory until a `storage.DatabaseTransaction` is committed or discarded. This leads to a large memory overhead when using a large database transaction (ex: getting all the `Coins` in a transaction). This PR changes our logic to instead reclaim memory as soon as the value is read so it can be reused.
=> [Storage] Optimize Memory usage on Transaction.Get

syncer/syncer.go
Props to @cindyxkuang for finding this bug!
In some cases, we were creating additional goroutines to sync blocks after `Wait` returned (causing a panic). This PR ensures we don't make this mistake by adding a lock to coordinate with the `addBlockIndices` goroutine.
=> [BUG] Fix syncer race condition

asserter/network_test.go, fetcher/account.go, fetcher/block.go, fetcher/construction.go, fetcher/errors.go, fetcher/fetcher_test.go, fetcher/mempool.go, fetcher/network.go
Fixes # .
errors overhaul in all other packages now allows `rosetta-cli` to check assertion errors without needing to use the generic ErrAssertionFailed
returning asserter errors in fetcher instead of generic ErrAssertionFailed
=> [fetcher] errors overhaul

asserter/errors.go, asserter/errors_test.go, fetcher/account.go, fetcher/block.go, fetcher/network.go, keys/errors.go, keys/errors_test.go, parser/errors.go, parser/errors_test.go, reconciler/errors.go, reconciler/errors_test.go, storage/errors.go, storage/errors_test.go, syncer/errors.go, syncer/errors_test.go
Fixes # .
following up on [https://github.com/coinbase/rosetta-sdk-go/pull/145/files#r486685115](https://github.com/coinbase/rosetta-sdk-go/pull/145/files#r486685115)
ex: `asserter.ErrAsserter` -> `asserter.Err`
=> rename Err() functions

asserter/account.go, asserter/block.go, asserter/construction.go, asserter/server.go, constructor/coordinator/coordinator.go, constructor/coordinator/coordinator_test.go, constructor/coordinator/types.go, constructor/job/errors.go, constructor/job/job.go, constructor/job/types.go, constructor/worker/worker.go, constructor/worker/worker_test.go, fetcher/construction.go, mocks/constructor/coordinator/helper.go
This PR adds support for "dry running" a transaction to get the `SuggestedFee` without actually signing or broadcasting it. This is useful for amending transactions in `UTXO-based` blockchains and for ensuring an account has sufficient funds in `account-based` blockchains.
=> [Constructor] Suggested Fee Dry Run

reconciler/reconciler.go, storage/balance_storage.go
This PR returns the `AccountIdentifier` and `Currency` in any balance fetching errors. This makes it a lot easier to debug issues with the `/account/balance` endpoint.
=> Put Account in Balance Fetch Error

storage/coin_storage.go, storage/compressor.go, storage/compressor_test.go
This PR changes `CoinStorage` to use an optimized encoding scheme instead of the standard `zstd` encoding. This significantly reduces the size of data stored on disk, utilizes much less memory, and is waaaaaay faster.
```text
Small Data (happy path):
Uncompressed: 147 B, Standard Compressed: 116 B, Optimized: 21 B
Complex Data (tons of metadata):
Uncompressed: 207 B, Standard Compressed: 137 B, Optimized: 41 B
```
```text
BenchmarkAccountCoinStandard
BenchmarkAccountCoinStandard-12            	   15799	     74628 ns/op	    2793 B/op	      29 allocs/op
BenchmarkComplexAccountCoinStandard
BenchmarkComplexAccountCoinStandard-12     	   15390	     80565 ns/op	    3597 B/op	      44 allocs/op
BenchmarkAccountCoinOptimized
BenchmarkAccountCoinOptimized-12           	 3039498	       373 ns/op …
```
=> [Storage] Optimize storage.AccountCoin Encoding

storage/badger_storage.go, storage/badger_storage_configuration.go, storage/badger_storage_test.go, storage/compressor.go, syncer/syncer.go
This PR overhauls the default BadgerDB settings to constrain storage-based memory usage to <= ~6 GB (which is harder than it sounds with BadgerDB). With the default BadgerDB settings, we found that RAM usage ballooned as DB sizes got large [> 200 GB] (often causing an OOM for unsuspecting users). From what we can tell, BadgerDB exclusively favors performance over resource usage and leaves it up to the user to adjust DB parameters to meet any resource restrictions. 
In `rosetta-sdk-go`, we care about performance as long as RAM usage is reasonable (many users of this package run it locally or in a CI/CD pipeline). Over the past month or so, we've been testing the options made available to us in Badger to find a good balance between performance and resource usage. Our new default settings …
=> [storage] Overhaul Badger Defaults

fetcher/block.go, fetcher/utils.go
This PR configures the `fetcher` to retry transient client errors (`EOF` and `connection reset by peer`). This PR also changes changes transaction fetching to automatically retry instead of aborting and retrying an entire block.
=> [Fetcher] Handle transient connection failures

fetcher/fetcher.go, fetcher/utils.go
This is a very small PR that returns more details about network mismatch when `InitializeAsserter` fails.
=> [Fetcher] Verbose network mismatch error

constructor/coordinator/coordinator.go, constructor/coordinator/coordinator_test.go, constructor/coordinator/errors.go, constructor/coordinator/types.go, constructor/job/types.go
Related: https://github.com/coinbase/rosetta-cli/issues/112
Related: https://github.com/coinbase/rosetta-cli/issues/119
A common request among `rosetta-cli` users has been the ability to trigger a `ReturnFunds` workflow after processing transactions so that funds can be returned to a faucet.
Almost all the lines added here are tests!
=> [Constructor] Return Funds Workflow

constructor/coordinator/coordinator.go, constructor/coordinator/coordinator_test.go
This PR fixes a small bug introduced #156 where we may attempt to create any workflow when calling `ReturnFunds`.
=> [BUG] Return Funds Workflow

constructor/coordinator/coordinator.go
This PR moves the check to determine if an account should be created to above the check for existing broadcasts. In practice, preventing account creation when pending broadcasts exist results in address creation stalling as soon as a few exist (as there is almost always a pended broadcast between a small set of accounts).
=> [Constructor] Move Create Account Before Broadcast Check

constructor/job/types.go, constructor/worker/worker.go, constructor/worker/worker_test.go
This PR adds support for reading ENVs and making HTTP requests while running workflows. This would allow anyone to make a request to a faucet during the `request_funds` workflow.
=> [Constructor] Load ENVs + Make HTTP Requests

statefulsyncer/stateful_syncer.go, storage/block_storage.go, storage/block_storage_test.go, storage/errors.go, storage/utils.go
Replaces: #161 
This PR includes a method for pruning `block_storage` that does not invalidate any of the [duplicate hash checks](https://github.com/coinbase/rosetta-cli#duplicate-hashes) performed by the `rosetta-cli`.
When syncing the first 120k blocks on `bitcoin-testnet`:
```
676M	pruned-bitcoin-data
1.3G	non-pruned-bitcoin-data
```
_Savings will increase dramatically the more block data is ingested (these sizes include all data stored by the `rosetta-cli`, not just block and transaction data)._
=> [Storage] Automatically Prune BlockStorage

keys/keys.go, keys/keys_test.go, statefulsyncer/stateful_syncer.go, storage/key_storage.go
Fixes #164 
This PR fixes a bug in `keys` where `Edwards25519` private keys are not imported correctly in `ImportPrivateKey`.
=> [BUG] [Keys] Import Private Key Error

Makefile, asserter/construction.go, asserter/construction_test.go, asserter/errors.go, asserter/utils.go, keys/errors.go, keys/keys.go, keys/signer_edwards25519_test.go, keys/signer_secp256k1_test.go
This PR fixes an issue where the PublicKey is all 0s when importing `edwards25519` keys. This bug was introduced in #93.
=> [Keys][Bug] Fix ImportPrivateKey

asserter/construction_test.go, storage/key_storage.go, utils/utils.go
This PR adds additional test coverage for the new zero bytes check introduced in #167.
=> [Asserter] Add more test coverage for BytesArrayZero

Makefile, storage/block_storage.go, utils/utils.go, utils/utils_test.go
To determine if we should begin running `check:construction`, we need to know if we are at tip. This PR adds a convenience function to the `utils` package that does this.
=> [Utils] Add util for checking if implementation at tip

constructor/coordinator/coordinator.go
#160 refactored `process` to defer db transaction discarding (and lock release), however, it introduced a regression where we would sleep while holding the lock (this can prevent block syncing). This PR moves sleep to `processLoop` so that the lock is released before sleeping. Props to @metajack for finding this issue!
=> [Constructor] Don't sleep with lock

constructor/coordinator/coordinator.go, utils/utils.go, utils/utils_test.go
Related Issue: https://github.com/coinbase/rosetta-cli/issues/100
This PR adds a collection of new functions to the `utils` package that help in getting memory usage and estimating time to tip.
=> [Utils] Add collection of utils

asserter/error.go, asserter/error_test.go, asserter/errors.go, asserter/network.go, asserter/network_test.go, fetcher/account.go, fetcher/block.go, fetcher/construction.go, fetcher/errors.go, fetcher/mempool.go, fetcher/network.go, fetcher/utils.go
This PR adds `*types.Error` assertion to the `asserter` and `fetcher`. Importantly, we do not exit if we detect a mismatch and instead log the assertion failure so that we don't silence the error returned by the Rosetta implementation.
=> [Fetcher|Asserter] Assert any *types.Error returned is in /network/options

mocks/reconciler/handler.go, reconciler/configuration.go, reconciler/reconciler.go, reconciler/reconciler_test.go
This PR adds support for handling `BalanceExemptions` (added in #178) in the `reconciler`.
=> [reconciler] Add support for types.BalanceExemption

constructor/README.md, constructor/coordinator/coordinator.go, constructor/coordinator/coordinator_test.go, constructor/coordinator/errors.go
Relates: https://github.com/coinbase/rosetta-cli/issues/136
This PR relaxes the requirement that the caller must defined a `create_account` and `request_funds` workflow.
=> [constructor] Remove required workflows

storage/counter_storage.go
This PR adds an `ExemptReconciliationCounter` constant in the `storage` package.
=> [storage] Exempt Reconciliations Counter

constructor/dsl/dsl_test.go, constructor/dsl/errors.go, constructor/dsl/parser.go, constructor/dsl/testdata/simple.ros
This PR adds parsing support for any variable type, instead of just objects.
=> [constructor/dsl] Fix Variable Parsing

asserter/errors.go, asserter/network.go, asserter/network_test.go
This PR ensures an error is returned by the `asserter` if a `types.BalanceExemption` is provided by an implementation but `HistoricalBalanceLookup` is not supported.
=> [asserter] Error if no historical balance lookup with exemptions

fetcher/errors.go
When canceling the `fetcher` context, the error assertion check will print a ton of incorrect assertion failures. This PR skips assertion checking if `context.Canceled`.
=> [fetcher] Only log asserter error if not context.Canceled

reconciler/reconciler.go, reconciler/reconciler_test.go
This PR fixes a bug in the `reconciler` where we invoke the `ReconciliationFailed` handler after matching a `ReconciliationDifference` with a provided `*types.BalanceExemption`.
=> [BUG][reconciler] Balance Exemption Handling

fetcher/errors.go
When the client times out a request, it attempts to assert the error returned by the implementation although none exists. This PR does not attempt to assert `transientErrors`.
=> [fetcher] Don't assert transient errors

reconciler/configuration.go, reconciler/reconciler.go, reconciler/reconciler_test.go
After some performance analysis, we discovered that one of the biggest syncing bottlenecks for `rosetta-cli` is waiting on the unbuffered reconciliation queue channel. This PR ensures the reconciliation queue is always buffered so we don't block.
If clearing the reconciliation queue is important for your application, make sure the value of `reconciler.QueueSize()` is below some value before exiting.
=> [reconciler] Use buffered channel

client/client.go, templates/client/client.mustache
The `client` package returns an extremely unhelpful error when a Rosetta API implementation returns a non-JSON response:
```text
Error: unable to fetch block 642926: request failed: /block {“index”:642926} undefined response type: unable to sync to 23786798: unable to sync to 23786798
```
This PR ensures the `client` prints a verbose error when the `response type` is not supported.
=> [client] Verbose Response Type Error

statefulsyncer/stateful_syncer.go, storage/block_storage.go, storage/block_storage_test.go, storage/errors.go
Related: https://github.com/coinbase/rosetta-sdk-go/pull/187
To avoid accessing pruned blocks, we need to set the pruneable index to be less than the last reconciled index.
=> [statefulsyncer/storage] Support dynamic pruning depth

storage/badger_storage.go
This PR adds a new "performance" storage mode that uses settings closer to the Badger defaults. This is used in the new "performance" mode on the `rosetta-cli` to improve syncing speed for users with more available RAM.
=> [storage] Add Performance Mode Config

storage/badger_storage.go
Related: #191 
This PR ensures the max table size is extended for the "performance settings".
=> [storage] Extend max table size in performance options

mocks/reconciler/helper.go, reconciler/reconciler.go, reconciler/reconciler_test.go, storage/balance_storage.go, storage/balance_storage_test.go, storage/block_storage.go, storage/block_storage_test.go
Related: #187 
As a result of using buffered channels in the reconciler, we need to protect against "out of date" updates to the `last_reconciled` information in storage.
=> [storage] Only update last reconciled if index >

reconciler/reconciler.go, reconciler/reconciler_test.go, storage/counter_storage.go
This PR ensures that accounts being reconciled when context is canceled are re-added to their respective reconciliation queue instead of being dropped (this can lead to a < 100% coverage with certain `rosetta-cli` end conditions).
=> [reconciler] Re-enqueue accounts when context canceled

asserter/asserter.go, asserter/asserter_test.go, asserter/block.go, asserter/block_test.go, asserter/error_test.go, asserter/errors.go, asserter/network.go, asserter/network_test.go, client/client.go, codegen.sh, constructor/coordinator/coordinator_test.go, fetcher/block_test.go, parser/balance_changes_test.go, storage/balance_storage_test.go, storage/coin_storage_test.go, templates/types.txt, types/allow.go, types/error.go, types/types.go
This PR updates `rosetta-sdk-go` to use [`rosetta-specifications@v1.4.6`](https://github.com/coinbase/rosetta-specifications/releases/tag/v1.4.6).
=> [Chore] Update to rosetta-specifications@v1.4.6

constructor/coordinator/coordinator_test.go, parser/balance_changes_test.go, parser/exemptions.go, parser/exemptions_test.go, parser/intent_test.go, parser/parser.go, reconciler/configuration.go, reconciler/reconciler.go, reconciler/reconciler_test.go, storage/balance_storage.go, storage/balance_storage_test.go, storage/errors.go
This PR extends `BalanceStorage` to update computed balances with an updated live balance if an account is subject to a `*types.BalanceExemption`.
=> [storage] Automated Computed Balance Updates

mocks/reconciler/handler.go, reconciler/configuration.go, reconciler/reconciler.go, reconciler/reconciler_test.go, storage/counter_storage.go
This PR ensures no reconciliations "enter the abyss". We now invoke the new `ReconciliationSkipped` handler if we opt to skip reconciliation for any account.
=> [reconciler] Skip Handler

storage/badger_storage.go, storage/badger_storage_test.go, storage/balance_storage.go, storage/balance_storage_test.go, storage/broadcast_storage.go, storage/coin_storage.go, storage/key_storage.go, storage/storage.go
After exposing the number of "skipped" reconciliations in the last release, it became abundantly clear that the `rosetta-cli` wastes up to 50% of all the calls it makes because accounts have been updated before they are able to make an /account/balance request. This PR modifies balance storage to track historical balances for all accounts.
As a side note, this PR unblocks the ability for `rosetta-bitcoin` to serve historical balance queries out of the box!
=> [storage] Historical Balance Tracking

mocks/reconciler/helper.go, reconciler/configuration.go, reconciler/errors.go, reconciler/reconciler.go, reconciler/reconciler_test.go
This PR updates the reconciler to use the new historical balance lookup functionality exposed by `BalanceStorage`(#202).
=> [reconciler] Remove ErrAccountUpdated

storage/balance_storage.go, storage/balance_storage_test.go
Because many blockchains apply rewards after the parent block is processed (usually before transactions in the next block are applied), adjusting the computed balance to equal the live balance of the parent block before applying balance changes doesn't guarantee that a computed account balance won't go negative (if a transaction in the new block spends the new rewards). This PR modifies the balance exemption logic to compare the computed balance after applying operations but before being checked for a negative value.
=> [storage] Balance Exemption Overhaul

storage/balance_storage.go, storage/balance_storage_test.go, storage/block_storage.go
This PR adds the ability to make a lazy block fetch in the context of a `storage.DatabaseTransaction` and allows for not setting the balance of an account if it doesn't exist when making calls to `GetBalance`.
=> [storage] BlockLazyTransactional + SetIfEmpty

storage/badger_storage.go, storage/balance_storage.go, storage/block_storage.go, storage/block_storage_test.go, storage/coin_storage.go
This PR updates the `storage` package to perform concurrent compression of items on write instead of performing compression serially. In practice, this can increase the **sync speed by 5-10x** (usually increasing even more if using a more powerful CPU).
=> [storage] Concurrent Compression on Write

storage/block_storage.go
This PR adds the method `CanonicalBlockTransactional` to `BlockStorage`.
=> [storage] Add CanonicalBlockTransactional

parser/balance_changes.go, storage/balance_storage.go, storage/balance_storage_test.go
This PR fixes an issue where the `parser` can cause a negative balance error when handling a block re-org.
=> [parser/storage] Orphan Block Pointer Overwrite

mocks/reconciler/helper.go, reconciler/reconciler.go, reconciler/reconciler_test.go, storage/block_storage.go, storage/block_storage_test.go
It is possible that the `reconciler` could query an account balance at an index not known to a Rosetta implementation if any balance queries are made before the `syncer` processes a node re-org. This PR ensures we treat these as "skipped" reconciliations instead of failures.
If a failure occurs because of some re-org (and we are querying balance at an index ahead of tip), we will retry the skipped reconciliation when the balance changes from the replacement blocks are added.
=> [reconciler] Skip on Live Balance Fetch Errors at Tip

reconciler/reconciler.go, reconciler/reconciler_test.go, reconciler/types.go, utils/bst.go, utils/bst_test.go
This PR fixes a potential race condition in the optimistic balance pruning logic. This was observed in our own testing when syncing and reconciling with high concurrency.
=> [reconciler] Fix Pruning Race

reconciler/reconciler.go, reconciler/reconciler_test.go
This PR fixes an inactive pruning race (where the active reconciliation loop prunes a balance being used by the inactive reconciliation loop).
=> [reconciler] Inactive Pruning Race + Inactive Pruning Support

statefulsyncer/stateful_syncer.go, storage/block_storage.go, storage/block_storage_test.go, syncer/configuration.go, syncer/syncer.go
This PR makes it possible to configure the reorg depth that the `syncer` can handle.
=> [syncer] Configurable Reorg Depth

reconciler/reconciler.go, reconciler/reconciler_test.go, reconciler/types.go
This PR fixes a regression in #221 where inactive reconciliation could result in pruning. It is a bad idea to prune during inactive reconciliation because we may accidentally prune the only historical balance record of an account (in active reconciliation there is always a new change stored).
=> [reconciler] Don't Prune During Inactive Reconciliation

Makefile, reconciler/reconciler_test.go, syncer/syncer.go, syncer/syncer_test.go
This PR makes a much more aggressive attempt to fix a flaky test that #224 did not fix. TL;DR tests of concurrent processing is hard.
```
go test -v ./reconciler/... -run PruningRaceConditionInactive -count 30 -race
```
=> [chore] Fix Flaky Test (part 2)

client/api_account.go, client/api_block.go, client/api_call.go, client/api_construction.go, client/api_mempool.go, client/api_network.go, client/client.go, fetcher/account_test.go, fetcher/errors.go, fetcher/utils.go, templates/client/api.mustache, templates/client/client.mustache
In some cases, intermediate services will return a 502, 503, or 504 HTTP status code before making a request to a Rosetta implementation. This can cause clients to error hard instead of retrying gracefully. This PR ensures we treat these errors as retriable.
=> [client/fetcher] Retry 502, 503, and 504 HTTP Codes

asserter/account.go, asserter/account_test.go, asserter/asserter.go, asserter/asserter_test.go, asserter/block_test.go, asserter/errors.go, asserter/events.go, asserter/events_test.go, asserter/search.go, asserter/search_test.go, asserter/server.go, asserter/server_test.go, examples/server/main.go, fetcher/account.go, fetcher/account_test.go, fetcher/events.go, fetcher/events_test.go, fetcher/search.go, fetcher/search_test.go
Related: #231 
This PR adds support for new endpoints in the `fetcher` and `asserter` package.
=> [chore] v1.4.7 Upgrade (Part 2)

asserter/server.go, asserter/server_test.go, client/client.go, codegen.sh, fetcher/search_test.go, types/operator.go, types/search_transactions_request.go, types/types.go, types/utils.go
This PR updates `rosetta-sdk-go` to [`rosetta-specifications@v1.4.8`](https://github.com/coinbase/rosetta-specifications/releases/tag/v1.4.8).
=> [chore] rosetta-specifications@v1.4.8

syncer/syncer.go
In #228, we introduced a regression into `syncer` where a `non-nil` error could be silenced by `context.Canceled`. This PR fixes this regression.
In short, we were always calling `context.Cancel()` when `syncer.Sync` returned (with `defer`). Because of the extra locking on exit added in #228, this delayed the return of `Sync` but not the invocation of cancel. This caused other functions to return with a non-nil error before `syncer.Sync` (which had the useful error) and `rosetta-cli` to return `context.Canceled` as the error instead of something interesting (as the [expected behavior](https://godoc.org/golang.org/x/sync/errgroup#Group.Wait) of `errgroup` is to return the first non-nil error from `Wait`).
=> [syncer] Only invoke cancel when successful

go.mod, go.sum, storage/encoder.go
Closes: #243
This PR updates `msgpack` to the latest release and resolves breaking API changes.
=> [chore] Update msgpack

utils/priority_mutex.go, utils/priority_mutex_test.go
In an effort to optimize `rosetta-cli` performance, we discovered that a priority lock could be used to prioritize the "hot path" (i.e. the syncing loop). This PR adds a basic implementation of such a lock called `PriorityMutex`.
=> [utils] Implement PriorityMutex

utils/priority_mutex.go, utils/priority_mutex_map.go, utils/priority_mutex_map_test.go, utils/priority_mutex_test.go
This PR implements a new data structure called a `MutexMap`. `MutexMap` allows the caller to acquire a global lock across any number of `*PriorityMutex` and to identify locks by some identifier (which enables very fine-grained locking). This data structure can be used to implement concurrent, non-conflicting database transactions in `storage`.
In a subsequent PR, we will implement another new data structure called `ShardedMap` that removes the need to acquire a global lock on `entries`.
=> [utils] Add MutexMap

fetcher/utils.go, statefulsyncer/configuration.go, statefulsyncer/stateful_syncer.go, storage/counter_storage.go, syncer/configuration.go, syncer/syncer.go, syncer/types.go
This PR adds a variadic function configuration option to `statefulsyncer` and adds support for configuring a custom pruning interval.
=> [statefulsyncer] Add Variadic Initializer

constructor/coordinator/coordinator_test.go, constructor/worker/worker_test.go, storage/badger_storage.go, storage/badger_storage_configuration.go, storage/badger_storage_test.go, storage/balance_storage.go, storage/balance_storage_test.go, storage/block_storage.go, storage/block_storage_test.go, storage/broadcast_storage.go, storage/broadcast_storage_test.go, storage/coin_storage.go, storage/coin_storage_test.go, storage/counter_storage.go, storage/job_storage.go, storage/job_storage_test.go, storage/key_storage.go, storage/storage.go
This PR updates the `storage` interface to provide access to more granular database locking and updates all files in `storage` to use this new interface.
Overhaul `BlockStorage`, `BalanceStorage`, and `CoinStorage` to use `WriteTransaction` to reduce usage of global locking (i.e. pruning/reconciliation don't need to acquire the global database lock).
=> [storage] Interface Overhaul

go.mod, go.sum, parser/balance_changes.go, storage/modules/balance_storage.go
Related: #252 
This PR completes the `Future Work` section of #252.
=> [storage] Small Nits

go.mod, go.sum, keys/signer_secp256k1.go, keys/signer_secp256k1_test.go
This PR is to support Zilliqa schnorr signature algorithm.
Add `Sign` and `Verify` functions for `secp256k1` by using zilliqa golang sdk.
=> feat: support schnorr_1 for zilliqa

reconciler/reconciler.go, reconciler/reconciler_test.go, reconciler/types.go, statefulsyncer/stateful_syncer.go, storage/modules/balance_storage.go, storage/modules/block_storage.go, storage/modules/coin_storage.go, storage/modules/counter_storage.go
This PR introduces performance optimizations in the `reconciler` that reduce lock contention in the syncing loop. This PR also migrates `BalanceStorage`, `BlockStorage`, and `CoinStorage` to use `github.com/neilotoole/errgroup` (in practice, significantly reduces memory usage without impacting performance).
=> [reconciler] Performance Overhaul

reconciler/reconciler.go, storage/modules/balance_storage.go, storage/modules/balance_storage_test.go, storage/modules/counter_storage.go
This PR fixes a few miscellaneous issues found while integrating `rosetta-sdk-go` into `rosetta-cli` (https://github.com/coinbase/rosetta-cli/pull/193).
=> [chore] Miscellaneous Nits Before Release

asserter/block.go, asserter/block_test.go
Related: #231 
This PR adds backwards compatibility for implementations that populate the `Operation.Status` field in the `/construction/parse` response. This support was accidentally removed when upgrading the `rosetta-sdk-go` to support `rosetta-specifications@v1.4.7`.
=> [asserter] Backwards Compatibility for Operation.Status

storage/modules/block_storage.go
This PR improves significantly improves block pruning performance by flattening the storage of transaction records. This new modeling approach means we no longer need to fetch a record before we prune it!
=> [storage] Block Pruning Optimization

client/api_account.go, client/api_block.go, client/api_call.go, client/api_construction.go, client/api_events.go, client/api_mempool.go, client/api_network.go, client/api_search.go, templates/client/api.mustache
This PR updates `client` to treat a [`408`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/408) as `ErrRetriable`.
=> [client] Handle 408 Status Code as Retriable

reconciler/reconciler.go
This PR fixes a few bugs in the `reconciler` that can halt syncing and/or prevent shutdown. Shoutout to @yflinn 
for posting about these issues!
=> [BUG][reconciler] Handle Skipped Reconciliations Correctly

mocks/reconciler/helper.go, reconciler/reconciler.go, reconciler/reconciler_test.go, reconciler/types.go
This PR adds support for forcing inactive reconciliation eventhough it may not be strictly required (based on the inactive reconciliation configuration). This is helpful for exiting with a certain reconciliation coverage from tip in `rosetta-cli`.
=> [reconciler] Inactive Reconciliation Bypass

storage/database/badger_database.go
To support blockchains with large blocks, we need to increase the table size configuration in `storage/database`. 
This ONLY affects `rosetta-cli` when `disable_memory_limit` is set to `true`!
=> [database] Update BadgerDB Performance Settings

asserter/asserter_test.go, asserter/errors.go, asserter/network.go, asserter/search.go, asserter/search_test.go, client/client.go, codegen.sh, types/block_response.go, types/operation.go, types/search_transactions_response.go, types/sync_status.go, types/types.go
This PR updates `rosetta-sdk-go` to the [latest release of `rosetta-specifications`](https://github.com/coinbase/rosetta-specifications/releases/tag/v1.4.9). This is a pretty minor release compared to other recent releases.
- Return `Synced` Status [`#71`](https://github.com/coinbase/rosetta-specifications/pull/71)
- [indexer] Add `total_count` field [`#70`](https://github.com/coinbase/rosetta-specifications/pull/70)
=> [chore] `rosetta-specifications@v1.4.9`

mocks/storage/modules/block_worker.go, storage/modules/balance_storage.go, storage/modules/balance_storage_test.go, storage/modules/block_storage.go, storage/modules/block_storage_test.go, storage/modules/broadcast_storage.go, storage/modules/broadcast_storage_test.go, storage/modules/coin_storage.go, storage/modules/coin_storage_test.go, storage/modules/counter_storage.go
This PR updates `BlockWorkers` to use a single `errgroup` when adding/removing a block instead of a unique one for each worker (requiring synchronization at the end of each worker spawn).
=> [storage] Single Errgroup Pool for BlockWorkers

storage/errors/errors.go, storage/modules/balance_storage.go, storage/modules/balance_storage_test.go
Someone was able to [force a panic in `rosetta-cli` because of an unpopulated BalanceStorage helper and handler](https://community.rosetta-api.org/t/operation-status-must-be-empty-for-construction/315/4?u=patrick.ogrady). This PR causes BalanceStorage to raise an error in these cases instead of panicking.
=> [storage] Protect against nil Helper and/or Handler in BalanceStorage

fetcher/configuration.go, fetcher/errors.go, fetcher/fetcher.go, fetcher/network_test.go
This PR allows the caller to specify that all non-200 responses from a Rosetta implementation should be retried. This is particularly useful when accessing a Rosetta implementation through a load balancer where there may be periods of inconsistency (i.e. we get a network status from one implementation and query another that has not yet synced the most recent block).
* Add `force_retry` to `rosetta-cli`
=> [fetcher] Optionally Force Retry

constructor/coordinator/types.go, constructor/job/types.go, constructor/worker/types.go, constructor/worker/worker.go, constructor/worker/worker_test.go, mocks/constructor/coordinator/helper.go, mocks/constructor/worker/helper.go
Related: https://github.com/coinbase/rosetta-cli/issues/205
This PR adds support for transactionally setting/getting arbitrary JSON across `workflows`. There is more context on why this is useful on the attached issue.
=> [constructor] Transactional KV Store

constructor/dsl/dsl_test.go, constructor/dsl/parser.go, constructor/dsl/testdata/simple.ros
Related: #276 
This PR adds support for `set_blob` and `get_blob` to the Rosetta DSL parser.
=> [constructor] Add `set_blob` and `get_blob` to DSL

storage/modules/block_storage.go, storage/modules/block_storage_test.go
This PR fixes a regression introduced by #269 where `FindTransaction` returns a pruning-related error when querying for a transaction added in the same `DatabaseTransaction`. Turns out we never testing `FindTransaction` in the same way it is called in `BroadcastStorage`.
=> [bug][storage] Fix `FindTransaction` Regression

keys/errors.go, keys/keys.go, keys/signer_secp256r1.go, keys/signer_secp256r1_test.go
This PR is to support `secp256r1` curve for `keys` package
Add `ImportPrivateKey`, `GenerateKeypair`, `Sign` and `Verify` functions for `secp256r1` by using golang ecdsa package
=> feat(keys): support secp256r1

reconciler/reconciler.go, reconciler/reconciler_test.go, reconciler/types.go, storage/errors/errors.go
1. There is a bug in our reconciliation logic around missing accounts. When an interesting account is configured, the reconciler may stop with an error like below:
`Error: unable to get computed balance for &{Address:0000000001 SubAccount:<nil>, Metadata:map[]}: &{Symbol: ICP Decimals:8 Metadata:map[]}: block nil`
The reconciler reconciles interesting accounts at every block height. But, there is no entry for an account in balance storage until it is encountered in a block. So, when the reconciler tries to reconcile an interesting account, it hasn't encountered yet, it stops with an account missing error (`ErrAccountMissing`).
2. The error message for `ErrAccountMissing` incorrectly says "block nil". 
1. Updated the reconciliation logic to skip reconciliation for missing accounts.
2. …
=> Skip reconciliation when interesting account is missing

storage/modules/block_storage.go, storage/modules/block_storage_test.go
Fixes # .
Previously, searching for transactions in unsynced blocks would return an error saying that the transaction was in a pruned block. Really, the transactions are present but in blocks past the synced head, which should return no transaction but with no error.
Additional check for if transaction seen in unseen block.
=> Transactions in unsynced blocks no-longer assumed pruned

utils/utils.go, utils/utils_test.go
Fixes # .
We added CheckNetworkTip and CheckStorageTip utility functions to DRY these checks in the Rosetta CLI. These methods return a block identifier if the network or storage block is at tip respectively. 
In some contexts, the CLI needs to know the block identifier even if it is not at tip.
Updated these methods to return at-tip status in addition to the network or storage block identifier.
=> Update check tip util functions to return both at-tip status and block id

asserter/block.go, asserter/block_test.go, asserter/errors.go, storage/errors/errors.go, storage/modules/block_storage.go, storage/modules/block_storage_test.go
This change adds the FindRelatedTransactions function to block storage, which will allow for related transaction processing in the future. This change also adds a duplicate check for related transactions to the asserter.
By checking all forward and backward relations, FindRelatedTransactions finds the highest block that must be confirmed to confirm a given transaction.
=> Add FindRelatedTransactions Function for Block Storage

fetcher/fetcher.go, fetcher/fetcher_test.go
When creating a fetcher instance, we always override the `Transport` of the `http.Client` present inside the `APIClient` object. This leads to unexpected behavior when callers provide their own `http.Client` via the `WithClient` option.
This change makes it so that we do not override the Transport when it is already provided . Note we still update the Transport's `TLSClientConfig` field when `insecureTLS` is set to true.
=> Do not override the provided HTTP client in the fetcher

fetcher/configuration.go, fetcher/fetcher.go, fetcher/fetcher_test.go
Fixes nil pointer dereference when initializing fetcher with timeout (PROTO-2135).
Currently when we initialize the fetcher, the rosetta client might not exist yet https://github.com/coinbase/rosetta-sdk-go/blob/master/fetcher/fetcher.go#L96. However when we initialize the fetcher with the timeout option, it tries to dereference the rosetta client which could result in nil pointer dereference panic https://github.com/coinbase/rosetta-sdk-go/blob/master/fetcher/configuration.go#L76.
The issue could be reproduced by pulling the latest rosetta-sdk-go and rosetta-cli, and running utils:asserter-configuration on rosetta-cli.
Instead of setting timeout on the rosetta client directly during fetcher initialization, store it as a field on the fetcher and set it on the rosetta client later when …
=> Fix nil pointer dereference when initializing fetcher with timeout

asserter/asserter.go, asserter/block.go, asserter/block_test.go, asserter/data/validation_balanced_related_ops.json, asserter/data/validation_fee_and_payment_balanced.json, asserter/data/validation_fee_and_payment_unbalanced.json, asserter/errors.go
Fixes # .
Currently we don't flag an asset if it doesn't have related operations implemented. Implementing related operations is optional, we only need it to be implemented if we have multiple outputs or we don't distinguish between sends/receives. In that case, ChainIO will break because it uses related operations to enforce a DAG structure on the operations.
Make related operations support configurable. If a related_operations_enabled is set to true in validator file, then throw error if related operations key doesn't exist. Otherwise, just print warning.
=> Related ops checks

types/utils.go, types/utils_test.go, utils/utils.go
Fixes https://github.com/coinbase/rosetta-cli/issues/230
When using rosetta with cosmos-sdk based blockchains with coins minted after Genesis rosetta-cli tests error because of missing account balances. 
To solve this issue, instead of returning an error when searching for a balance for a currency that doesn't have a value return a 0 amount.  This means that if rosetta looks for the amount of a currency at a block height before it has been minted it will simply return a 0 amount.
=> Fix: Use amount of 0 for currencies not listed

asserter/block.go
Fixes # .
#374 
#374 was not building so created a new PR
=> remove unwanted logging

constructor/dsl/dsl_test.go, constructor/dsl/parser.go, constructor/dsl/testdata/action_valid.ros
Fixes https://github.com/coinbase/rosetta-cli/issues/248
To improve the parsing logic for `set_variable` action types
Before splitting the string to determine if the remaining line contains an arithmetic operator, we first check to see if the remaining line (sans `;` suffix) is valid JSON
Is there any possibility of arithmetic and JSON in the same line?
=> Improve parsing logic for `set_variable` action types

storage/modules/balance_storage.go, storage/modules/balance_storage_test.go, utils/utils.go
Fixes .
https://github.com/coinbase/rosetta-cli/issues/259 
https://github.com/coinbase/rosetta-cli/issues/260 
For motivation please refer #365 
We commit transaction for bootstrap balances in chunks of 600 accounts.
I tested it locally with `MaxEntrySizePerTxn` to be lower/same than number of account and it worked. I still have not found a clean way to unit test that since that value comes from a const.
=> Bootstrap file memory issues

go.mod, go.sum, server/api.go
Fixes # .
The earlier version of https://github.com/coinbase/kryptology did not support building rosetta-cli in multiple os/platforms. This was stopping us to release rosetta-cli
Updated https://github.com/coinbase/kryptology to v1.8.0
Tested using this commit version in rosetta-cli
=> update kryptology to v1.8.0

parser/match_operations.go
https://jira.coinbase-corp.com/browse/ROSE-230
Currently we use amount.Value == "0" to check if an amount matches zero. This caused an issue in ChainIO as we may have "-0" as input. To resolve the issue, we need to convert string to integer and then compare.
=> ROSE-230: Use integer to compare amount sign

mocks/utils/fetcher_helper.go, storage/modules/coin_storage.go, storage/modules/coin_storage_test.go, utils/utils.go
Fixes # .
https://jira.coinbase-corp.com/browse/ROSE-231 
'Insufficient fund' error for prefunded_account in UTXO chain
See PR
=> ROSE-231: Call /account/coins endpoint to add account coin info in coin storage

parser/match_operations.go, parser/match_operations_test.go
Fixes #403  .
In some rosetta implementation `sub account` field is optional. This means we can't predict if it will be there or not. The current matcher logic requires it to be either required or not required. 
Added a flag called `SubAccountOptional` which if set to `true` will ignore the subaccount matching and if false, behaves exactly as before
=> add sub account optional flag

server/README.md
"Controller" was missing a letter in one instance.
=> Fix typo in /server/README.md

README.md
This PR updates the README file to match the Rosetta Team SDK template.
=> [ROSE-445] Readme template update

README.md, client/api_account.go, client/api_block.go, client/api_call.go, client/api_construction.go, client/api_events.go, client/api_mempool.go, client/api_network.go, client/api_search.go, client/client.go, client/configuration.go, templates/client/api.mustache, templates/client/client.mustache, templates/client/configuration.mustache
Error handling improvement for client package
=> Error handling improvement for client package

fetcher/account.go, fetcher/block.go, fetcher/call.go, fetcher/construction.go, fetcher/errors.go, fetcher/events.go, fetcher/fetcher.go, fetcher/mempool.go, fetcher/network.go, fetcher/search.go, keys/errors.go, keys/keys.go, keys/signer_edwards25519.go, keys/signer_pallas.go, keys/signer_pallas_test.go, keys/signer_secp256k1.go, keys/signer_secp256r1.go, keys/types.go
Error handling for fetcher and keys packages
=> Error handling for fetcher and keys packages

parser/balance_changes.go, parser/intent.go, parser/match_operations.go, reconciler/errors.go, reconciler/reconciler.go, reconciler/reconciler_test.go
Error handling improvement for parser and reconciler packages
=> Error handling improvement for parser and reconciler packages

asserter/block.go, constructor/worker/populator.go, constructor/worker/worker.go, constructor/worker/worker_test.go, fetcher/utils.go, parser/intent.go, storage/database/badger_database.go, storage/encoder/encoder.go, storage/errors/errors.go, storage/errors/errors_test.go, storage/modules/balance_storage.go, storage/modules/block_storage.go, storage/modules/block_storage_test.go, storage/modules/broadcast_storage.go, storage/modules/coin_storage.go, storage/modules/counter_storage.go, storage/modules/job_storage.go, storage/modules/key_storage.go, storage/modules/utils.go, types/utils.go, utils/utils.go
Error handling improvement for storage and util packages
=> Error handling improvement for storage and util packages

asserter/server.go, asserter/server_test.go, types/construction_preprocess_request.go
Fixes # .
remove these two fields according to specifications changes
=> [types]remove two fields in preprocess request

constructor/dsl/dsl.go, fetcher/utils.go, parser/intent.go, reconciler/reconciler.go, storage/modules/balance_storage.go, storage/modules/broadcast_storage.go
=> Error handling refactor

asserter/block.go, asserter/errors.go, asserter/server_test.go
Make block identifier asserter function comply with Rosetta spec
=> Make block identifier asserter function comply with Rosetta spec

Makefile, codegen.sh, go.mod, go.sum, templates/go.mod.types, types/go.mod, types/go.sum
Fixes #460  .
`rosetta-sdk-go` dependency graph is quite big and all of them are not useful for rosetta development.  This makes it hard to use `rosetta-sdk-go`
Make `types` as go submodule so that people can just import `types` independent of `rosetta-sdk-go`
=> make types a go module

fetcher/errors.go, statefulsyncer/stateful_syncer.go, syncer/syncer.go
Fixes # .
check:data
before fix
after fix
check:construction 
before fix
after fix
=> fix uncessary context canceled err

client/api_account.go, client/api_block.go, client/api_call.go, client/api_construction.go, client/api_events.go, client/api_mempool.go, client/api_network.go, client/api_search.go, constructor/worker/worker.go, examples/server/main.go, fetcher/block.go, templates/client/api.mustache
This commit guarantees the order of transactions in the block endpoint. This can benefit clients in a certain way. For example, some Rosetta client requires transaction kept in order so that they can identify the coinbase (lower-case c) transaction in one block.
It does so by creating a map of fetched transactions and using that map to return the transactions in the original order they had in the block.
- Added a new struct `FetchedTransaction` to represent fetched transactions
- Updated `fetchChannelTransactions` to use the new `FetchedTransaction` struct
- Updated `UnsafeTransactions` to use the new `FetchedTransaction` struct and create a map of fetched transactions
- Modified the return statement in `UnsafeTransactions` to use the fetched transactions from the map
This PR also …
=> Guarantee the order of transactions in the block endpoint

asserter/asserter.go
=> Add funcitionality to create a new generic asserter

Makefile, asserter/asserter.go, constructor/worker/worker_test.go, examples/server/main.go, fetcher/block.go, go.mod, go.sum, headerforwarder/context_headers.go, headerforwarder/forwarder.go, headerforwarder/response_writer.go, server/api_account.go, server/api_block.go, server/api_call.go, server/api_construction.go, server/api_events.go, server/api_mempool.go, server/api_network.go, server/api_search.go, server/routers.go, templates/server/controller-api.mustache, templates/server/routers.mustache
In order to support some common use cases, Mesh servers need the ability to pass request headers through to the native nodes, and to return headers from native node requests back to the caller.
Use cases:
* **passing a client ID header to the nodes** — this client ID shouldn't originate with the Mesh server since it may have many different callers, so it should be passed through to the native node requests
* **sticky session cookies** — to support sticky sessions on native nodes, AWS uses cookies. Cookies are managed by the `Cookie` and `Set-Cookie` headers, which will need to be passed from the caller to the native node, and returned from the native node ALB to the caller
The `HeaderForwarder` type extracts headers from potentially many native node requests and adds them to a Mesh …
=> feat(header forwarding): add HeaderForwarder and plumbing

asserter/block.go
Configuring a generic Asserter without a genesis block results in a nil pointer exception on this line.
Add a nil check
=> fix: add nil check to block asserter

headerforwarder/forwarder.go
This utility was part of a proof-of-concept and this is an attempt to move it closer to a production-ready state
Header forwarder was failing with `fatal error: concurrent map writes` when under heavy load. This change adds a read/write aware locking mechanism to prevent concurrent writes (concurrent reads will not block unless there is a write happening)
=> fix: add sync.RWMutex to headerforwarder map

headerforwarder/forwarder.go, headerforwarder/forwarder_test.go, headerforwarder/response_writer.go, headerforwarder/response_writer_test.go
This utility was part of a proof-of-concept and this is an attempt to move it closer to a production-ready state
`HeaderForwarder` and `headerforwarder.ResponseWriter` were not tested, lacking specific code/documentation about edge cases
This PR adds those tests and fixes some issues uncovered by the testing
=> chore: add unit tests to headerforwarder package

client/client.go, codegen.sh, types/types.go
This synchronizes the un-updated api.json to be the correct version (see how it's 1.4.13 on the previous 1.4.15 version)
=> Update mesh-specification version to 1.5.1
