- README.md
> Update new logo

- README.md
> Adjust width setting

- fetcher/construction.go
- storage/coin_storage_test.go
Fixes # .
applying same change as this PR: [https://github.com/coinbase/rosetta-sdk-go/pull/98](https://github.com/coinbase/rosetta-sdk-go/pull/98)
> exposing Rosetta errors in construction endpoints of fetcher

- fetcher/construction.go
- storage/coin_storage_test.go
Fixes # .
applying changes from [https://github.com/coinbase/rosetta-sdk-go/pull/110](https://github.com/coinbase/rosetta-sdk-go/pull/110)
> returning fetcher.Error on all construction endpoints

- go.mod
- go.sum
- keys/errors.go
- keys/keys.go
- keys/keys_test.go
- keys/signer_edwards25519.go
- keys/signer_edwards25519_test.go
- keys/signer_secp256k1.go
- keys/signer_secp256k1_test.go
- storage/balance_storage_test.go
- utils/utils_test.go
Fixes # .
adding typed errors improves the debugging experience for developers who can better determine where a particular error is coming from
continuing from [this PR](https://github.com/coinbase/rosetta-sdk-go/pull/102)
added errors.go in keys
> Rosetta SDK errors overhaul: keys

- storage/badger_storage.go
This PR ensures that only 1 memtable is every kept in memory. With the increased `MaxTableSize` setting for the performance option, this was causing vastly increased memory usage (and OOM'ing with 16 GB RAM).
> [Storage] Update Badger Defaults

- keys/errors.go
- keys/keys.go
- keys/keys_test.go
- storage/badger_storage.go
- storage/balance_storage.go
- storage/block_storage.go
- storage/broadcast_storage.go
- storage/coin_storage.go
- storage/compressor.go
- storage/errors.go
- storage/errors_test.go
- storage/job_storage.go
- storage/key_storage.go
Fixes # .
continuing from [https://github.com/coinbase/rosetta-sdk-go/pull/134](https://github.com/coinbase/rosetta-sdk-go/pull/134)
added errors.go file in `storage` package and unit test
> [Storage] error overhaul

- reconciler/errors.go
- reconciler/errors_test.go
- reconciler/reconciler.go
- storage/block_storage.go
- storage/errors.go
- syncer/errors.go
- syncer/errors_test.go
- syncer/syncer.go
- syncer/syncer_test.go
Fixes # .
continuing from [https://github.com/coinbase/rosetta-sdk-go/pull/138](https://github.com/coinbase/rosetta-sdk-go/pull/138)
added errors.go and corresponding unit tests for ErrSyncer/ErrReconciler
> [reconciler][syncer][storage] remaining error handling

- fetcher/errors.go
- fetcher/errors_test.go
- parser/errors.go
- reconciler/errors.go
- storage/errors.go
- syncer/errors.go
Fixes # .
adding Err() in fetcher allows us to error check more elegantly in rosetta-cli
> added Err() in fetcher plus small fixes

- types/utils.go
- types/utils_test.go
Fixes # .
typo in error message causing tests to fail in client code
> corrected error message in utils.go

- fetcher/utils.go
When the fetcher retries a request, there is no way to know how many prior attempts have been made. This PR logs this information!
> [Fetcher] Log retry attempts

- constructor/coordinator/coordinator.go
This PR refactors `process` so that `defer` can be used to discard the dbTx transaction. With the addition of `ReturnFunds`, we were seeing some db locking as the dbTx was not always discarded on exit (dbTx's acquire a write lock).
> [BUG][Constructor] Ensure DbTx is Discarded

- go.mod
- go.sum
> [Chore] Update go-ethereum

- storage/balance_storage.go
- storage/balance_storage_test.go
Related: #198 
This PR fixes a regression introduced in #198 and adds a test to ensure we catch this regression in the future.
> [storage] Respect Bootstrapped Balance

- storage/balance_storage.go
- storage/balance_storage_test.go
- storage/errors.go
This PR adds support for historical state pruning in balance storage.
> [storage] Prune Historical Balances

- reconciler/reconciler_test.go
This PR introduces a fix for a flaky test introduced in #223.
> [reconciler] Fix Flaky Test

- mocks/utils/fetcher_helper.go
- utils/utils.go
- utils/utils_test.go
This PR updates `FetcherHelper` to use the updated `AccountBalanceRetry` method in `fetcher` (as of #231).
> [utils] Update `FetcherHelper`

- .circleci/config.yml
- asserter/errors.go
- client/configuration.go
- parser/errors.go
- parser/match_operations.go
- storage/errors.go
- templates/client/configuration.mustache
This PR updates `golangci-lint` to `v1.32.2` and fixes any new linting issues.
> [chore] Update golangci-lint to `v1.32.2`

- asserter/README.md
- asserter/asserter.go
Fixes # .
Add documentation explaining asserter validations
> add asserter validation doc

- constructor/dsl/README.md
- constructor/worker/worker.go
Fixes # .
Update the logging from `Did you forget to fund?` to `Please fund the address ` and update DSL Readme.md to let developers know they need to use prefunded account.
> [Chore] Add better logging for prefunding an address

- reconciler/reconciler.go
The reconciler does not enqueue inactive accounts for blockchains that do not support inactive balance lookup. 
Moving this enqueue code above the highWaterMark code ensures all accounts are added to the inactive queue. There’s no chain in behavior for blockchains that support inactive balance lookup. All tests are passing.
> Always add accounts to inactive reconciler queue

- CONTRIBUTING.md
- types/signing_payload.go
Fixes # .
Improve contribution guidelines
Update contribution guidelines to run `make gen`
> [chore] update contribution guide to run make gen

- asserter/block.go
- asserter/block_test.go
- asserter/errors.go
Fixes # .
Fee op shouldn't have related_operation field
added validation for the above scenario in the asserter.
> fee should't have related op

- client/client.go
- codegen.sh
- types/allow.go
- types/block_identifier.go
- types/case.go
- types/curve_type.go
- types/sync_status.go
- types/types.go
Fixes # .
Rosetta specification update
Updates rosetta specification to [1.14.12](https://github.com/coinbase/rosetta-specifications/releases/tag/v1.4.12)
- Adds hashcase to SDK
- Adds `Pallas` curve to curveType
> update spec to 1.4.12

- .circleci/config.yml
Fixes # .
Ubuntu 14.04 EOL. upgrade circle ci
> [chore] upgrade ubuntu

- CONTRIBUTING.md
- README.md
Updated the README and CONTRIBUTING files to encourage developer contribution.
Want to increase developer contributions.
Added more information on how to contribute.
Please offer feedback as to whether the improvements are helpful.
> Update SDK README and CONTRIBUTING files

- storage/database/badger_database.go
Fixes # .
6GB will lead to errors in AWS env
change to 3gb
> change tablesize default

- statefulsyncer/stateful_syncer.go
- syncer/errors.go
- syncer/syncer.go
- syncer/syncer_test.go
Implement error handling improvement for Syncer and StatefulSyncer packages
> Error handling improvement for Syncer and StatefulSyncer

- asserter/account.go
- asserter/account_test.go
- asserter/asserter.go
- asserter/asserter_test.go
- asserter/block.go
- asserter/coin.go
- asserter/coin_test.go
- asserter/construction.go
- asserter/construction_test.go
- asserter/error.go
- asserter/errors.go
- asserter/events.go
- asserter/mempool.go
- asserter/network.go
- asserter/network_test.go
- asserter/search.go
- asserter/server.go
- asserter/server_test.go
- asserter/utils.go
Error handling improvement for asserter package
> Error handling improvement for asserter package

- constructor/coordinator/coordinator.go
- constructor/coordinator/errors.go
- constructor/dsl/dsl.go
- constructor/dsl/dsl_test.go
- constructor/dsl/errors.go
- constructor/dsl/parser.go
- constructor/job/errors.go
- constructor/job/job.go
- constructor/job/utils.go
- constructor/worker/errors.go
- constructor/worker/populator.go
- constructor/worker/worker.go
- constructor/worker/worker_test.go
Error handling improvement for constructor related packages
> Error handling improvement for constructor related packages

- constructor/coordinator/coordinator.go
- constructor/coordinator/errors.go
> Improve error message

- templates/docs/server.md
> Update server.md for renaming
